CONTANT:
  SERVER_IP: localhost
  REDIS_IP: 59.110.68.237
  PASSWORD: 123456

spring:
  profiles:
    active: 8011
  redis:
    host: ${CONTANT.REDIS_IP}
    port: 6379
    timeout: 30000
    password: 123
    database: 15